name: movies_app
description: "Movie App with BLoC"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  dio: ^5.4.2
  retrofit: ^4.1.0
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  flutter_dotenv: ^5.1.0
  pretty_dio_logger: ^1.3.1
  easy_localization: ^3.0.5
  go_router: ^13.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/i18n/
